# This is a minor change to trigger a rebuild
title: Maggie Will Design
description: Maggie Williams Portfolio  
baseurl: "" # 
url: "https://yourusername.github.io" # 

# Build settings
theme: minima
