# This is a minor change to trigger a rebuild
title: Maggie Will Design
description: Design Portfolio of Maggie Williams
baseurl: "" # the subpath
url: "https://maggiewilldesign.github.io" # the base hostname & protocol 

# Build settings
theme: minima
