# This is a minor change to trigger a rebuild new
title: Maggie Will Design
description: Maggie Williams Portfolio  
baseurl: "" # 
url: "https://maggiewilldesign.github.io" # 

# Build settings
theme: minima
